configfile: "config/config.yaml"


include: "rules/0_initialization.smk"


rule all:
    input:
        expand(
            config["results_dir"] + "0_initialization/{sample}/{sample}.h5mu",
            sample=config["samples"],
        ),
