data_dir: "/home/brandon/data/pingyin/snmultiome/input/"
results_dir: "results/"

samples:
  - 1619LM
  - 1619MM
  - 1633LM
  - 1633MM-repeat

RNA:
  celltypist_model: "Human_Endometrium_Atlas.pkl"
  qc_filters:
    min_genes: 200
    pct_counts_mt: 5
    pct_counts_ribo: 5
    doublet_score: 0.3

ATAC:
  blacklist: "resources/hg38-blacklist.v2.bed"
  qc_filters:
    min_tsse: 5
    min_counts: 1000